### PR TITLE
Integ ink

### PR DESCRIPTION
**Pull request by kimtang**

### CODE REVIEW

**Comment by kimtang** [comment]
I have added ink (https://github.com/JunoLab/atom-ink) and vega (https://vega.github.io/) support for this atom package. Would be happy to see this merged into master.

**Comment by quintanar401** [comment]
Thanks for your pull request. Ink seems to be a good feature but it looks like it is much more powerful and actually can replace my Result View entirely. Have you considered adding Ink console instead of the view (via a config param of course)? Not sure though if it can accommodate large tables...

As for vega - it seems to be out of scope of this package. I'd suggest to make a plugin from it then those who need it would turn it on (it will be possible to reuse it in other places too, ink console, panes and etc).  I was going to do something like this with atom-charts package. It is quite easy, if you are unfamiliar with atom packages I can help.

**Comment by kimtang** [comment]
>>> Have you considered adding Ink console

Ink console is good but it looks like that the project itself is not maintained for a long time. So switching to ink console might be a risk.

 

>>> I'd suggest to make a plugin

Sounds good to me. Unfortunately I do not know how to do it. Need time to investigate then.

 

Kim

**Comment by quintanar401** [comment]
I can add kdb-chart to git, it was basically ready, you can either clone it or copy the required parts.

Also atom has a command to create a new package, you may use it directly.

**Comment by kimtang** [comment]
Yes please. I will just extend it with vega and ink

**Comment by quintanar401** [comment]
added (atom-charts), may add you as a developer.

ink can be merged with connect-kdb, just remove vega from this request

**Comment by quintanar401** [comment]
keep toJSON here too

**Comment by kimtang** [comment]
As discussed with quintanar401 I will resend a pulll request with vega remove

**Pull request closed without merging**
